name: dart_normalizer
description: Dart port of normalizr library https://github.com/paularmstrong/normalizr
version: 0.9.1
author: Ivan Serbyniuk
homepage: https://github.com/ivanserbyniuk/dart_normalizer

environment:
  sdk: '>=1.24.0 <3.0.0'

dev_dependencies:
  test: '>=0.12.24+2 <2.0.0'
